const cars = [
    {
        id: 1,
        brand: "Toyota",
        model: "Camry",
        year: 2024,
        type: "Sedan",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 55,
        location: "New York",
        available: true,
        mileage: 12500,
        image: "/cars/toyota-camry.jpg"
    },
    {
        id: 2,
        brand: "Honda",
        model: "Civic",
        year: 2023,
        type: "Sedan",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 48,
        location: "Los Angeles",
        available: true,
        mileage: 18200,
        image: "/cars/honda-civic.jpg"
    },
    {
        id: 3,
        brand: "Ford",
        model: "Mustang",
        year: 2024,
        type: "Sports",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 4,
        doors: 2,
        pricePerDay: 95,
        location: "Miami",
        available: true,
        mileage: 8700,
        image: "/cars/ford-mustang.jpg"
    },
    {
        id: 4,
        brand: "BMW",
        model: "3 Series",
        year: 2024,
        type: "Luxury Sedan",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 110,
        location: "Chicago",
        available: true,
        mileage: 9600,
        image: "/cars/bmw-3-series.jpg"
    },
    {
        id: 5,
        brand: "Mercedes-Benz",
        model: "C-Class",
        year: 2023,
        type: "Luxury Sedan",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 125,
        location: "Boston",
        available: true,
        mileage: 11400,
        image: "/cars/mercedes-c-class.jpg"
    },
    {
        id: 6,
        brand: "Tesla",
        model: "Model 3",
        year: 2024,
        type: "Electric",
        transmission: "Automatic",
        fuel: "Electric",
        seats: 5,
        doors: 4,
        pricePerDay: 85,
        location: "San Francisco",
        available: true,
        mileage: 7200,
        image: "/cars/tesla-model-3.jpg"
    },
    {
        id: 7,
        brand: "Toyota",
        model: "RAV4",
        year: 2024,
        type: "SUV",
        transmission: "Automatic",
        fuel: "Hybrid",
        seats: 5,
        doors: 4,
        pricePerDay: 72,
        location: "Seattle",
        available: true,
        mileage: 10400,
        image: "/cars/toyota-rav4.jpg"
    },
    {
        id: 8,
        brand: "Honda",
        model: "CR-V",
        year: 2023,
        type: "SUV",
        transmission: "Automatic",
        fuel: "Hybrid",
        seats: 5,
        doors: 4,
        pricePerDay: 70,
        location: "Denver",
        available: true,
        mileage: 15600,
        image: "/cars/honda-crv.jpg"
    },
    {
        id: 9,
        brand: "Jeep",
        model: "Wrangler",
        year: 2024,
        type: "SUV",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 90,
        location: "Las Vegas",
        available: true,
        mileage: 8300,
        image: "/cars/jeep-wrangler.jpg"
    },
    {
        id: 10,
        brand: "Chevrolet",
        model: "Tahoe",
        year: 2023,
        type: "Full-size SUV",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 7,
        doors: 4,
        pricePerDay: 115,
        location: "Dallas",
        available: true,
        mileage: 19200,
        image: "/cars/chevrolet-tahoe.jpg"
    },
    {
        id: 11,
        brand: "Hyundai",
        model: "Elantra",
        year: 2024,
        type: "Sedan",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 42,
        location: "Houston",
        available: true,
        mileage: 6800,
        image: "/cars/hyundai-elantra.jpg"
    },
    {
        id: 12,
        brand: "Kia",
        model: "Sportage",
        year: 2023,
        type: "SUV",
        transmission: "Automatic",
        fuel: "Hybrid",
        seats: 5,
        doors: 4,
        pricePerDay: 65,
        location: "Atlanta",
        available: true,
        mileage: 13100,
        image: "/cars/kia-sportage.jpg"
    },
    {
        id: 13,
        brand: "Nissan",
        model: "Altima",
        year: 2023,
        type: "Sedan",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 45,
        location: "Phoenix",
        available: true,
        mileage: 17400,
        image: "/cars/nissan-altima.jpg"
    },
    {
        id: 14,
        brand: "Audi",
        model: "A4",
        year: 2024,
        type: "Luxury Sedan",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 105,
        location: "Washington D.C.",
        available: true,
        mileage: 5900,
        image: "/cars/audi-a4.jpg"
    },
    {
        id: 15,
        brand: "Volkswagen",
        model: "Tiguan",
        year: 2023,
        type: "SUV",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 62,
        location: "Philadelphia",
        available: true,
        mileage: 14800,
        image: "/cars/volkswagen-tiguan.jpg"
    },
    {
        id: 16,
        brand: "Ford",
        model: "Explorer",
        year: 2024,
        type: "SUV",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 7,
        doors: 4,
        pricePerDay: 88,
        location: "Orlando",
        available: true,
        mileage: 9100,
        image: "/cars/ford-explorer.jpg"
    },
    {
        id: 17,
        brand: "Lexus",
        model: "RX 350",
        year: 2024,
        type: "Luxury SUV",
        transmission: "Automatic",
        fuel: "Hybrid",
        seats: 5,
        doors: 4,
        pricePerDay: 120,
        location: "San Diego",
        available: true,
        mileage: 6400,
        image: "/cars/lexus-rx350.jpg"
    },
    {
        id: 18,
        brand: "Mazda",
        model: "CX-5",
        year: 2023,
        type: "SUV",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 58,
        location: "Portland",
        available: true,
        mileage: 16300,
        image: "/cars/mazda-cx5.jpg"
    },
    {
        id: 19,
        brand: "Porsche",
        model: "911 Carrera",
        year: 2024,
        type: "Sports",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 2,
        doors: 2,
        pricePerDay: 250,
        location: "Los Angeles",
        available: true,
        mileage: 3200,
        image: "/cars/porsche-911.jpg"
    },
    {
        id: 20,
        brand: "Range Rover",
        model: "Sport",
        year: 2024,
        type: "Luxury SUV",
        transmission: "Automatic",
        fuel: "Gasoline",
        seats: 5,
        doors: 4,
        pricePerDay: 180,
        location: "New York",
        available: true,
        mileage: 5100,
        image: "/cars/range-rover-sport.jpg"
    }
];
export default cars;